### ISSUE TITLE
InvalidStateError("Server Closed")

### ISSUE THREAD

**Issue by mahesh-co1** [footniko/mediasoup-sample#14]
MediaSoup server is listening on port 8080!
New socket connection: {
  roomId: 'room1',
  peerName: 'Alice',
  EIO: '3',
  transport: 'polling',
  t: 'NDCzB2K'
}
/path/to/appdata/config/workspace/mediasoup-sample/server/node_modules/mediasoup/lib/Server.js:255
			throw new errors.InvalidStateError('Server closed');
			^

klass [InvalidStateError]: Server closed
    at Server.Room (/path/to/appdata/config/workspace/mediasoup-sample/server/node_modules/mediasoup/lib/Server.js:255:10)
    at Namespace.<anonymous> (/path/to/appdata/config/workspace/mediasoup-sample/server/index.js:38:24)
    at Namespace.emit (events.js:314:20)
    at Namespace.emit (/path/to/appdata/config/workspace/mediasoup-sample/server/node_modules/socket.io/lib/namespace.js:213:10)
    at /path/to/appdata/config/workspace/mediasoup-sample/server/node_modules/socket.io/lib/namespace.js:181:14
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by ygavrishov** [comment]
I got the same error. How did you fix it?
