### ISSUE TITLE
frontend npm start

### ISSUE THREAD

**Issue by SnaiCrys** [footniko/mediasoup-sample#5]
Can't start frontend app

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mediasoup-frontend@0.0.1~prestart: mediasoup-frontend@0.0.1
6 info lifecycle mediasoup-frontend@0.0.1~start: mediasoup-frontend@0.0.1
7 verbose lifecycle mediasoup-frontend@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle mediasoup-frontend@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/gta/media-sfu/mediasoup-sample/frontend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle mediasoup-frontend@0.0.1~start: CWD: /home/gta/media-sfu/mediasoup-sample/frontend
10 silly lifecycle mediasoup-frontend@0.0.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle mediasoup-frontend@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle mediasoup-frontend@0.0.1~start: Failed to exec start script
13 verbose stack Error: mediasoup-frontend@0.0.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid mediasoup-frontend@0.0.1
15 verbose cwd /home/gta/media-sfu/mediasoup-sample/frontend
16 verbose Linux 4.15.0-39-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error mediasoup-frontend@0.0.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the mediasoup-frontend@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

After install i have WARN

```
npm WARN mediasoup-frontend@0.0.1 No repository field.

added 48 packages from 36 contributors and audited 121 packages in 0.989s
found 0 vulnerabilities

```

**Comment by SnaiCrys** [comment]
Oh, I have another Express app on same port
